"""
Django settings for electro_bootstrap project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file if present (cPanel's "Setup Python App" screen sets
# real env vars directly, so this is mainly for local dev / other hosts).
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def _env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the old insecure dev key only when DJANGO_SECRET_KEY isn't set,
# so local development keeps working without a .env file.
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-x)is0-g@nsit@gnq56z75*c0sbgf82lav+rgvp+qb_gpfn31$%',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'store',
]

JAZZMIN_SETTINGS = {
    'site_title': 'Urban Pantry Admin',
    'site_header': 'Urban Pantry',
    'site_brand': 'Urban Pantry',
    'welcome_sign': 'Welcome to the Urban Pantry control room',
    'copyright': 'Urban Pantry',
    'site_logo_classes': 'brand-image img-circle elevation-2',
    'search_model': ['store.Product', 'store.Order', 'store.Category'],
    'topmenu_links': [
        {'name': 'View site', 'url': 'home', 'icon': 'fas fa-external-link-alt'},
        {'name': 'Shop', 'url': 'shop', 'icon': 'fas fa-store'},
    ],
    'custom_links': {
        'store': [
            {'name': 'View storefront', 'url': 'home', 'icon': 'fas fa-external-link-alt'},
        ],
    },
    'show_sidebar': True,
    'navigation_expanded': True,
    'order_with_respect_to': ['store', 'auth'],
    'icons': {
        'store': 'fas fa-store',
        'store.product': 'fas fa-box-open',
        'store.category': 'fas fa-tags',
        'store.order': 'fas fa-receipt',
        'store.emailtemplate': 'fas fa-envelope-open-text',
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
    },
    'custom_css': 'css/admin.css',
    'custom_js': None,
    'use_google_fonts_cdn': True,
    # The UI builder's control-sidebar panel isn't taken out of document flow
    # in this Jazzmin/AdminLTE version, which breaks the .app-wrapper grid's
    # column sizing (it stretches the sidebar column to fit the hidden
    # panel's width, pushing all page content way off to the right/down).
    # We ship a fixed navy/brass theme via admin.css, so the live theme
    # builder isn't needed anyway.
    'show_ui_builder': False,
    'show_theme_chooser': False,
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'navbar_small_text': False,
    'sidebar_nav_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'footer_small_text': False,
    'accent': 'accent-primary',
    'navbar': 'navbar-white navbar-light',
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_legacy_style': False,
    'sidebar_fixed': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'electro_bootstrap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'electro_bootstrap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Set DB_ENGINE=mysql (with DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT) for
# cPanel/production. Falls back to local sqlite when DB_ENGINE is unset, so
# local development needs no extra configuration.

if os.getenv('DB_ENGINE') == 'mysql':
    import pymysql
    pymysql.install_as_MySQLdb()

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', ''),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# `collectstatic` writes here; on cPanel point Apache/your domain's static
# alias at this folder, or just let WhiteNoise serve it (default below).
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles'))
# Static files are always served by WhiteNoise. Uploaded media (product
# images) goes to an S3-compatible bucket when BUCKET_NAME is set (Railway
# Buckets in production), otherwise to the local filesystem for development.
_STATICFILES_STORAGE = {
    # Compression without the strict cache-busting manifest: some vendored
    # static assets (e.g. lightbox.min.js) reference a missing .map file,
    # which the manifest variant refuses to build around.
    'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
}

if os.getenv('BUCKET_NAME'):
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': os.getenv('BUCKET_NAME'),
                'endpoint_url': os.getenv('BUCKET_ENDPOINT', 'https://t3.storageapi.dev'),
                'access_key': os.getenv('BUCKET_ACCESS_KEY_ID'),
                'secret_key': os.getenv('BUCKET_SECRET_ACCESS_KEY'),
                'region_name': os.getenv('BUCKET_REGION', 'auto'),
                # Railway buckets are private: serve images via short-lived
                # signed URLs instead of making the bucket public.
                'default_acl': None,
                'querystring_auth': True,
                'querystring_expire': int(os.getenv('BUCKET_URL_EXPIRE', '3600')),
                'file_overwrite': False,
                'signature_version': 's3v4',
                'addressing_style': 'virtual',
            },
        },
        'staticfiles': _STATICFILES_STORAGE,
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': _STATICFILES_STORAGE,
    }

MEDIA_URL = '/media/'
# User-uploaded files (product images, etc). On cPanel this should be a
# writable folder outside the git-deployed code, e.g. via DJANGO_MEDIA_ROOT.
MEDIA_ROOT = Path(os.getenv('DJANGO_MEDIA_ROOT', str(BASE_DIR / 'media')))

# Trust the reverse proxy header cPanel/Passenger sets for HTTPS detection.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', True)
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', False)

PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Urban Pantry <no-reply@urbanpantry.com>')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'

# Send errors (with tracebacks) to stdout so they show up in Railway's
# deploy logs. Without this, DEBUG=False hides 500 errors completely.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
