# Generated by Django 6.1 on 2026-08-20 14:19

from django.db import migrations, models


def seed_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('store', 'EmailTemplate')
    EmailTemplate.objects.get_or_create(
        key='order_confirmation',
        defaults={
            'subject': 'Urban Pantry order #{{ order_id }} confirmed',
            'body': 'Hello {{ customer_name }},\n\nThank you for shopping with Urban Pantry. Your order #{{ order_id }} is confirmed.\n\n{{ items }}\n\nOrder total: N{{ total }}\n\nWe will keep you updated as it moves forward.\n\nUrban Pantry',
        },
    )


def seed_demo_inventory(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Product.objects.filter(stock_quantity=0).update(stock_quantity=10)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_email_templates, migrations.RunPython.noop),
        migrations.RunPython(seed_demo_inventory, migrations.RunPython.noop),
    ]
